services:
  # The Flask Web Server service
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: us-central1-docker.pkg.dev/tomiwa-contract-monitor/my-docker-repo/dashboard-web:v3
    platform: linux/amd64
    ports:
      - "5001:5000"
    volumes:
      # Mount the local .env file into the container
      - ./.env:/app/.env
      # Mount the database file to persist data
      - ./events.db:/app/events.db
    restart: always

  # The Python Listener service
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: us-central1-docker.pkg.dev/tomiwa-contract-monitor/my-docker-repo/dashboard-worker:v3
    platform: linux/amd64
    volumes:
      - ./.env:/app/.env
      - ./events.db:/app/events.db
    restart: always