# using an official lightweight Python image
FROM python:3.11-slim

# setting the working directory inside the container
WORKDIR /app

# leveraging Docker's layer caching
COPY requirements.txt .

# install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# copy the rest of the application code into the container
COPY . .

# expose the port the app runs on
# use an ENV variable that Cloud Run provides.
ENV PORT 8080
EXPOSE 8080

# use Gunicorn, a production-ready web server, to run the app
# it will run the 'app' object from the 'dashboard.py' file
CMD exec gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 0 dashboard:app