# using an official lightweight Python image
FROM python:3.11-slim

# setting the working directory inside the container
WORKDIR /app

# leveraging Docker's layer caching
COPY requirements.txt requirements.txt

# install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# copy the rest of the application code into the container
COPY . .

# expose the port the app runs on
EXPOSE 5000

# Use Gunicorn, a production-ready web server, to run the app
# It will run the 'app' object from the 'dashboard.py' file
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "dashboard:app"]
